# Generated by Django 5.2.1 on 2026-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alert_source_other_and_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Received by District Office', 'Received by District Office'), ('Under Review', 'Under Review'), ('More Information Requested', 'More Information Requested'), ('Converted to Case', 'Converted to Case'), ('Referred to Relevant Office', 'Referred to Relevant Office'), ('Closed - No Further Action', 'Closed - No Further Action'), ('Duplicate / Already Known', 'Duplicate / Already Known'), ('Emergency Response Initiated', 'Emergency Response Initiated'), ('Ready for Intake', 'Ready for Intake'), ('Intake In Progress', 'Intake In Progress'), ('Pending Supervisor Review', 'Pending Supervisor Review'), ('Approved for Allocation', 'Approved for Allocation'), ('Allocated to Case Officer', 'Allocated to Case Officer'), ('Rejected', 'Rejected')], default='Submitted', max_length=80),
        ),
    ]
