# Generated by Django 5.2.1 on 2026-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='nearest_landmark',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
