# Generated by Django 5.2.1 on 2026-05-27 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_ward_provinces(apps, schema_editor):
    Ward = apps.get_model('core', 'Ward')
    for ward in Ward.objects.select_related('district'):
        if ward.district_id and ward.district.province_id:
            ward.province_id = ward.district.province_id
            ward.save(update_fields=['province'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_case_execution_drafts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_districts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_districts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='province',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_provinces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='province',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='province',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='province',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_provinces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_wards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='core.province'),
        ),
        migrations.AddField(
            model_name='ward',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='ward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_wards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_ward_provinces, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CommunityChildcareWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180)),
                ('national_id', models.CharField(blank=True, max_length=80)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ccws', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccws', to='core.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ccws', to='core.province')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_ccws', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ccws', to='core.ward')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=180)),
                ('court_type', models.CharField(choices=[('Magistrates Court', 'Magistrates Court'), ("Children's Court", "Children's Court"), ('High Court', 'High Court'), ('Community Court', 'Community Court'), ('Other', 'Other')], max_length=80)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_courts', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='core.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='core.province')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_courts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('court_name',),
                'unique_together': {('district', 'court_name')},
            },
        ),
        migrations.CreateModel(
            name='PartnersInDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=180)),
                ('partner_type', models.CharField(choices=[('NGO', 'NGO'), ('Government Department', 'Government Department'), ('Hospital/Clinic', 'Hospital/Clinic'), ('Police/VFU', 'Police/VFU'), ('School', 'School'), ('Faith Based Organisation', 'Faith Based Organisation'), ('Community Based Organisation', 'Community Based Organisation'), ('Place of Safety', 'Place of Safety'), ('Legal Aid', 'Legal Aid'), ('Other', 'Other')], max_length=80)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('operating_area', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_district_partners', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_partners', to='core.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_partners', to='core.province')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_district_partners', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_partners', to='core.ward')),
            ],
            options={
                'ordering': ('partner_name',),
                'unique_together': {('district', 'partner_name')},
            },
        ),
    ]
