# Generated by Django 5.2.1 on 2026-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_communitychildcareworker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='court_type_other',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnersindistrict',
            name='partner_type_other',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnersindistrict',
            name='services_offered_other',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
