# Generated by Django 5.2.1 on 2026-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alert_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='internal_status',
            field=models.CharField(default='New', max_length=80),
        ),
    ]
