# Generated by Django 5.2.1 on 2026-06-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_normalize_alert_internal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='escalation_level',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='alert',
            name='escalation_notes',
            field=models.TextField(blank=True),
        ),
    ]
