# Generated by Django 5.2.1 on 2026-06-07 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alert_escalation_level_alert_escalation_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_grfm_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='closure_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CaseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField()),
                ('action_type', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('outcome', models.CharField(max_length=80)),
                ('responsible_person', models.CharField(blank=True, max_length=160)),
                ('next_step', models.CharField(blank=True, max_length=240)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_actions', to='core.alert')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-action_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CaseEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('escalated_to', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_escalations', to='core.alert')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_date', models.DateField()),
                ('method', models.CharField(max_length=80)),
                ('persons_contacted', models.CharField(blank=True, max_length=240)),
                ('findings', models.TextField()),
                ('internal_notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='core.alert')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_investigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-investigation_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CaseReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('expected_response_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=80)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_summary', models.TextField(blank=True)),
                ('outcome', models.CharField(default='Pending', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_referrals', to='core.alert')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_type', models.CharField(max_length=120)),
                ('resolution_summary', models.TextField()),
                ('corrective_action', models.TextField(blank=True)),
                ('citizen_message', models.TextField()),
                ('resolved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_resolutions', to='core.alert')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-resolved_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='core.alert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CitizenFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_status', models.CharField(max_length=80)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_feedback', to='core.alert')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
