# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alert_assigned_at_alert_assigned_by_alert_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="household_social_register",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="publicsubmission",
            name="household_social_register",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
